// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxiZYNh8iKzrik7I7TpEx_dt1DcQx13QY',
    appId: '1:780545128402:android:77848ba1cbf8b5c960fa0b',
    messagingSenderId: '780545128402',
    projectId: 'notemobile-388',
    storageBucket: 'notemobile-388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLwlrQwDcqAvZydNgrJyFjP9ynpA899Y',
    appId: '1:780545128402:ios:6efc397005803cf960fa0b',
    messagingSenderId: '780545128402',
    projectId: 'notemobile-388',
    storageBucket: 'notemobile-388.appspot.com',
    iosClientId:
        '780545128402-svfhvn0maudca6nqja1ndpooc2v9kr9i.apps.googleusercontent.com',
    iosBundleId: 'com.michalkrysinski.notemobile',
  );
}
